import 'dart:convert';

import 'package:flutter_test/flutter_test.dart';
import 'package:http/http.dart' as http;
import 'package:optionsschool/data/local/local_progress_repo.dart';
import 'package:optionsschool/data/models/lesson_progress.dart';
import 'package:optionsschool/data/repositories/progress_repo.dart';
import 'package:optionsschool/data/supabase/supabase_progress_repo.dart';
import 'package:optionsschool/engagement/streak.dart';
import 'package:shared_preferences/shared_preferences.dart';
import 'package:supabase_flutter/supabase_flutter.dart' as sb;

/// Progress sync against a stubbed PostgREST endpoint.
///
/// The point of these tests is the promise made to a learner on a train: a
/// finished lesson is never lost, and it reaches the server later.
void main() {
  TestWidgetsFlutterBinding.ensureInitialized();

  const String userId = 'user-1';
  const String lessonId = 'what-is-an-option';

  Map<String, dynamic> remoteRow({int correct = 2, int total = 2}) {
    return <String, dynamic>{
      'user_id': userId,
      'lesson_id': lessonId,
      'cards_viewed': 5,
      'lesson_completed': true,
      'quiz_completed': true,
      'correct_answers': correct,
      'total_questions': total,
      'quiz_attempts': 1,
      // Generated by Postgres: 20 deck + 2×10 correct + 15 perfect.
      'points_earned': 55,
      'last_opened_at': '2026-07-28T10:00:00Z',
      'completed_at': '2026-07-28T10:05:00Z',
      'updated_at': '2026-07-28T10:05:00Z',
    };
  }

  /// Builds the repo under test over a fake transport and a real local cache.
  Future<_Harness> harness(_Responder responder) async {
    SharedPreferences.setMockInitialValues(<String, Object>{});
    final SharedPreferences prefs = await SharedPreferences.getInstance();

    final _FakeHttpClient http = _FakeHttpClient(responder);
    final sb.SupabaseClient client = sb.SupabaseClient(
      'https://stub.supabase.co',
      'stub-publishable-key',
      httpClient: http,
    );
    addTearDown(client.dispose);

    final LocalProgressRepo cache = LocalProgressRepo(prefs);
    return _Harness(
      repo: SupabaseProgressRepo(client: client, cache: cache, prefs: prefs),
      cache: cache,
      prefs: prefs,
      http: http,
    );
  }

  group('reads', () {
    test('server rows are mapped, points included, and cached for offline', () async {
      final _Harness h = await harness(
        (http.BaseRequest request, String body) => _json(<Map<String, dynamic>>[
          remoteRow(),
        ]),
      );

      final Map<String, LessonProgress> all = await h.repo.loadAll(userId);

      final LessonProgress progress = all[lessonId]!;
      expect(progress.cardsViewed, 5);
      expect(progress.quizCompleted, isTrue);
      expect(progress.correctAnswers, 2);
      expect(progress.pointsEarned, 55);
      expect(progress.completedAt?.toUtc().hour, 10);

      // Warmed, so the next cold start works with no signal.
      final Map<String, LessonProgress> cached = await h.cache.loadAll(userId);
      expect(cached[lessonId]?.pointsEarned, 55);
    });

    test('a dropped connection falls back to the device copy', () async {
      final _Harness h = await harness(
        (http.BaseRequest request, String body) =>
            throw http.ClientException('no network'),
      );

      await h.cache.saveLesson(
        userId: userId,
        progress: const LessonProgress(
          lessonId: lessonId,
          lessonCompleted: true,
          pointsEarned: 20,
        ),
      );

      final Map<String, LessonProgress> all = await h.repo.loadAll(userId);
      expect(all[lessonId]?.pointsEarned, 20);
    });

    test('a streak date survives the round trip as a plain local day', () async {
      final _Harness h = await harness(
        (http.BaseRequest request, String body) => _json(<String, dynamic>{
          'user_id': userId,
          'current_streak': 4,
          'longest_streak': 9,
          'last_active_day': '2026-07-28',
          'freeze_available': false,
          'days_toward_freeze': 3,
        }),
      );

      final StreakState streak = (await h.repo.loadStreak(userId))!;
      expect(streak.current, 4);
      expect(streak.longest, 9);
      expect(streak.freezeAvailable, isFalse);
      expect(streak.daysTowardFreeze, 3);
      // Local midnight, exactly what StreakState.dateOnly produces — a streak
      // must not shift a day because of the reader's timezone.
      expect(streak.lastActiveDay, DateTime(2026, 7, 28));
    });
  });

  group('writes', () {
    test('points are never sent — the server computes them', () async {
      final _Harness h = await harness(
        (http.BaseRequest request, String body) =>
            _json(const <Map<String, dynamic>>[]),
      );

      await h.repo.saveLesson(
        userId: userId,
        // A tampered client claiming a big score.
        progress: const LessonProgress(
          lessonId: lessonId,
          lessonCompleted: true,
          correctAnswers: 2,
          totalQuestions: 2,
          pointsEarned: 99999,
        ),
      );

      final _Recorded post = h.http.recorded.lastWhere(
        (_Recorded r) => r.method == 'POST',
      );
      final Map<String, dynamic> row =
          jsonDecode(post.body) as Map<String, dynamic>;

      expect(row.containsKey('points_earned'), isFalse);
      expect(row['correct_answers'], 2);
      expect(row['user_id'], userId);
    });

    test('a streak is written as a date, not a timestamp', () async {
      final _Harness h = await harness(
        (http.BaseRequest request, String body) =>
            _json(const <Map<String, dynamic>>[]),
      );

      await h.repo.saveStreak(
        userId: userId,
        streak: StreakState(
          current: 2,
          longest: 2,
          lastActiveDay: DateTime(2026, 7, 30),
        ),
      );

      final _Recorded post = h.http.recorded.lastWhere(
        (_Recorded r) => r.method == 'POST',
      );
      final Map<String, dynamic> row =
          jsonDecode(post.body) as Map<String, dynamic>;
      expect(row['last_active_day'], '2026-07-30');
    });
  });

  group('offline writes', () {
    test('a lesson finished with no signal is kept and queued', () async {
      final _Harness h = await harness(
        (http.BaseRequest request, String body) =>
            throw http.ClientException('no network'),
      );

      await h.repo.saveLesson(
        userId: userId,
        progress: const LessonProgress(
          lessonId: lessonId,
          lessonCompleted: true,
          correctAnswers: 2,
          totalQuestions: 2,
          pointsEarned: 55,
        ),
      );

      // Nothing thrown, nothing lost.
      final Map<String, LessonProgress> cached = await h.cache.loadAll(userId);
      expect(cached[lessonId]?.lessonCompleted, isTrue);
      expect(
        h.prefs.getStringList('sync.pending_lessons.$userId'),
        <String>[lessonId],
      );
    });

    test('the queue is flushed on the next successful round trip', () async {
      bool online = false;
      final _Harness h = await harness((http.BaseRequest request, String body) {
        if (!online) throw http.ClientException('no network');
        return request.method == 'POST'
            ? _json(const <Map<String, dynamic>>[])
            : _json(<Map<String, dynamic>>[remoteRow()]);
      });

      await h.repo.saveLesson(
        userId: userId,
        progress: const LessonProgress(lessonId: lessonId, quizCompleted: true,
            correctAnswers: 2, totalQuestions: 2),
      );
      expect(h.prefs.getStringList('sync.pending_lessons.$userId'), isNotNull);

      online = true;
      h.http.recorded.clear();
      await h.repo.loadAll(userId);

      // The stranded row went up BEFORE the read, so a stale server row can
      // never overwrite fresher local work.
      expect(h.http.recorded.first.method, 'POST');
      expect(h.prefs.getStringList('sync.pending_lessons.$userId'), isNull);
    });

    test('an offline reset fails loudly instead of coming back later', () async {
      final _Harness h = await harness(
        (http.BaseRequest request, String body) =>
            throw http.ClientException('no network'),
      );

      await h.cache.saveLesson(
        userId: userId,
        progress: const LessonProgress(lessonId: lessonId, quizCompleted: true),
      );

      await expectLater(
        h.repo.clear(userId),
        throwsA(isA<ProgressException>()),
      );
      // The device copy survives: a wipe here would look successful and then be
      // undone by the next read from the untouched server.
      final Map<String, LessonProgress> cached = await h.cache.loadAll(userId);
      expect(cached[lessonId], isNotNull);
    });

    test('a rejection that is not a network problem is surfaced', () async {
      // 42501 = insufficient_privilege: an RLS policy said no. Queueing that
      // for retry would hide a bug behind an infinite retry loop.
      final _Harness h = await harness(
        (http.BaseRequest request, String body) => _json(
          <String, dynamic>{
            'code': '42501',
            'message': 'new row violates row-level security policy',
          },
          status: 403,
        ),
      );

      await expectLater(
        h.repo.saveLesson(
          userId: userId,
          progress: const LessonProgress(lessonId: lessonId),
        ),
        throwsA(isA<sb.PostgrestException>()),
      );
      expect(h.prefs.getStringList('sync.pending_lessons.$userId'), isNull);
    });
  });
}

// ---------------------------------------------------------------------------
// Test doubles
// ---------------------------------------------------------------------------

typedef _Responder =
    Future<http.StreamedResponse> Function(http.BaseRequest request, String body);

class _Harness {
  _Harness({
    required this.repo,
    required this.cache,
    required this.prefs,
    required this.http,
  });

  final SupabaseProgressRepo repo;
  final LocalProgressRepo cache;
  final SharedPreferences prefs;
  final _FakeHttpClient http;
}

class _Recorded {
  _Recorded(this.method, this.url, this.body);

  final String method;
  final Uri url;
  final String body;
}

/// Stands in for the network so no test ever opens a socket.
class _FakeHttpClient extends http.BaseClient {
  _FakeHttpClient(this._responder);

  final _Responder _responder;
  final List<_Recorded> recorded = <_Recorded>[];

  @override
  Future<http.StreamedResponse> send(http.BaseRequest request) async {
    final String body = request is http.Request ? request.body : '';
    recorded.add(_Recorded(request.method, request.url, body));

    final http.StreamedResponse response = await _responder(request, body);
    // postgrest reads `response.request` while parsing, so echo it back.
    return http.StreamedResponse(
      response.stream,
      response.statusCode,
      contentLength: response.contentLength,
      headers: response.headers,
      request: request,
    );
  }
}

Future<http.StreamedResponse> _json(Object? payload, {int status = 200}) async {
  final List<int> bytes = utf8.encode(jsonEncode(payload));
  return http.StreamedResponse(
    Stream<List<int>>.value(bytes),
    status,
    contentLength: bytes.length,
    headers: <String, String>{'content-type': 'application/json'},
  );
}
